name: Actualizar README

on:
  schedule:
    - cron: '* */12 * * *' #
  workflow_dispatch:

jobs:
  build:
    name: Actualizar el README  de este repositorio con la activida reciente
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
